services:
  - type: web
    name: mcdonalds-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: mcdonalds-ai-db
    databaseName: mcdonalds_ai
    ipAllowList: []
